config/urls.py
from django.contrib import admin

from django.urls import path,include


#書き方は教科書のP27を参照
#URLと処理の関係を入力していく。それがurls.py
#path(URL,実行する処理(さらに参照するurls.py),URL逆引き用の名前指定)
#allauthでのログインを実装させる
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls"),name="home"),
    path('movie/', include("movie.urls"),name="movie"),
    path('staff/', include("staff.urls"),name="staff"),
    path('shop/', include("shop.urls"),name="shop"),
    path('accounts/', include("allauth.urls")),
]

home/urls.py
from django.urls import path
from . import views

app_name    = "home"
urlpatterns = [ 
    path('', views.index, name="index"),
]

movie/urls.py
from django.urls import path
from . import views

app_name    = "movie"
urlpatterns = [ 
    path('', views.index, name="index"),
]

shop/urls.py
from django.urls import path
from . import views

app_name    = "shop"
urlpatterns = [ 
    path('', views.index, name="index"),
]

staff/urls.py
from django.urls import path
from . import views

app_name    = "staff"
urlpatterns = [ 
    path('', views.index, name="index"),
]

home/models.py
from django.db import models

# Create your models here.

movie/models.py
from django.db import models

# Create your models he
class Movie(models.Model):
    class Meta:
        #DBのテーブル名を指定する。マイグレーション時にmovieでテーブルが作られる。
        db_table    = "movie"
    #教科書P47~P48を参照
    #モデルフィールドを定義する。マイグレーションコマンドを実行をすることで、DBに反映できる。
    filename    = models.CharField(verbose_name="動画ファイル名(.mp4形式で記述)",max_length=200)
    title       = models.CharField(verbose_name="動画タイトル",max_length=20)
    description = models.CharField(verbose_name="動画説明", max_length=500,blank=True,default="")

    #管理画面で表示する時の文字列を定義する。
    #ここでは動画タイトル(title)を定義しているので、管理画面にアクセスするとDBに格納されてある動画タイトル全てが確認できる
    def __str__(self):
        return self.title

shop/models.py
from django.db import models

# Create your models here.
class Shop(models.Model):
    class Meta:
        #DBのテーブル名を指定する。マイグレーション時にmovieでテーブルが作られる。
        db_table    = "Shop"

    #教科書P47~P48を参照
    #モデルフィールドを定義する。マイグレーションコマンドを実行をすることで、DBに反映できる。
    filename        = models.CharField(verbose_name="画像ファイル名",max_length=200)
    goodsname       = models.CharField(verbose_name="商品の名前",max_length=30)
    price           = models.IntegerField(verbose_name="金額" )
    comment         = models.CharField(verbose_name="商品紹介", max_length=500)


    #管理画面で表示する時の文字列を定義する。
    def __str__(self):
        return self.goodsname

staff/models.py
from django.db import models

# Create your models here.
class Staff(models.Model):
    class Meta:
        #DBのテーブル名を指定する。マイグレーション時にmovieでテーブルが作られる。
        db_table    = "staff"

    #教科書P47~P48を参照
    #モデルフィールドを定義する。マイグレーションコマンドを実行をすることで、DBに反映できる。
    filename        = models.CharField(verbose_name="画像ファイル名",max_length=200)
    staffname       = models.CharField(verbose_name="スタッフの名前",max_length=30)
    bestmuscle      = models.CharField(verbose_name="チャームポイントなる筋肉名", max_length=20)
    workouthistory  = models.IntegerField(verbose_name="トレーニング歴")
    comment         = models.CharField(verbose_name="一言", max_length=300)

    #管理画面で表示する時の文字列を定義する。
    def __str__(self):
        return self.staffname

home/views.py
from django.shortcuts import render

# Create your views here.

#クラスベースのビューを作るため
from django.views import View

#Viewを継承してGET文、POST文の関数を作る
class HomeView(View):

    def get(self, request, *args, **kwargs):


        return render(request,"home/index.html")

    def post(self, request, *args, **kwargs):

        pass

index   = HomeView.as_view()

movie/views.py
from django.shortcuts import render

# Create your views here.
from django.views import View
from .models import Movie

#ログイン必須のページにする
from django.contrib.auth.mixins import LoginRequiredMixin



#DjangoのViewを継承する。クラスベースのビューを作る
#書き方については教科書のP35を参照

#LoginRequiredMixinを追加する。これで未ログインのユーザーはmovieのページにアクセスできない
class MovieView(LoginRequiredMixin,View):

    #GET文(URL指定でアクセスされたときの処理)
    def get(self,request,*args,**kwargs):
        
        if "id" in request.GET:
            #個別の動画ページレンダリングしてレスポンスを返す処理

            data    = Movie.objects.filter(id=request.GET["id"])
            context = { "data": data } 

            print(request.GET["id"])
            return render(request,"movie/content.html",context)

        else:

            print("GET文が送信されました")

            #models.pyのMovieで定義したフィールドに基づき、DBへアクセス
            #movieテーブルに格納されているデータを全て抜き取る
            data    = Movie.objects.all()

            #DBから手に入れたデータをテンプレート変数として渡すため、contextに辞書型として代入
            context = { "data" : data }

            #HTMLの集合体からウェブページを作るため、レンダリング処理をする
            #      レンダリングする(HTTPリクエスト、レンダリング対象のテンプレート、レンダリング対象に与える変数)
            return render(request,"movie/index.html",context)


#urls.pyから呼び出せるように、変数indexの中に処理を格納
index   = MovieView.as_view()

shop/views.py
from django.shortcuts import render

# Create your views here.

#クラスベースのビューを作るため
from django.views import View
from .models import Shop

#Viewを継承してGET文、POST文の関数を作る
class ShopView(View):

    def get(self, request, *args, **kwargs):

        data    = Shop.objects.all()
        context = { "data" : data }

        return render(request,"shop/index.html",context)

    def post(self, request, *args, **kwargs):

        pass

index   = ShopView.as_view()

staff/views.py
from django.shortcuts import render

# Create your views here.

#クラスベースのビューを作るため
from django.views import View
from .models import Staff

#Viewを継承してGET文、POST文の関数を作る
class StaffView(View):

    def get(self, request, *args, **kwargs):

        data    = Staff.objects.all()
        context = { "data" : data }

        return render(request,"staff/index.html",context)

    def post(self, request, *args, **kwargs):

        pass

index   = StaffView.as_view()

templates/common/l_sidebar.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{% block page_title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'common/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'common/css/l_sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'common/css/fontawesome/all.css' %}">

    <script src="{% static 'common/js/jquery-3.1.1.min.js' %}"></script>


    {% block extra_head %}{% endblock %}

</head>
<body>

    <header>
        <div id="title_area" class="title_area">
            <a class="sidebar_link" href="{% url 'home:index' %}" ><h1 class="title">レザーマチョナイズ</h1></a>
        </div>

        <input id="menu_button" class="menu_button" type="checkbox">
        <label class="menu_label" for="menu_button">
            <div class="menu_open_icon"><i class="fas fa-bars"></i></div>
            <div class="menu_close_icon"><i class="fas fa-times"></i></div>
        </label>

        <div id="menu_closer" class="menu_closer"></div>

        <!--メニューエリア PC表示時、左側に表示。SP表示時、サイドバーとして機能する-->
        <nav id="menu_area" class="menu_area">

            {% if user.is_authenticated %}
            <a class="sidebar_link" href="{% url 'account_logout' %}" ><div class="menu_content">会員サイトログアウト</div></a>
            {% elif user.is_anonymous %}
            <a class="sidebar_link" href="{% url 'account_login' %}" ><div class="menu_content">会員サイトログイン</div></a>
            {% endif %}

            <a class="sidebar_link" href="{% url 'home:index' %}" ><div class="menu_content">施設案内</div></a>
            <a class="sidebar_link" href="{% url 'staff:index' %}" ><div class="menu_content">スタッフ紹介</div></a>
            <a class="sidebar_link" href="{% url 'home:index' %}" ><div class="menu_content">トレーニングプラン</div></a>
            <a class="sidebar_link" href="{% url 'home:index' %}" ><div class="menu_content">採用情報</div></a>
            <a class="sidebar_link" href="{% url 'home:index' %}" ><div class="menu_content">ブログ</div></a>
            <a class="sidebar_link" href="{% url 'home:index' %}" ><div class="menu_content">SNSリンク</div></a>
            <a class="sidebar_link" href="{% url 'shop:index' %}" ><div class="menu_content">ショップ</div></a>

            <!--urls.pyで指定したname="movie"とname="index"が発動している-->
            <a class="sidebar_link" href="{% url 'movie:index' %}" ><div class="menu_content">トレーニング動画</div></a>
        </nav>
    </header>

    {% block main %}
    {% endblock %}

</body>
</html>

templates/home/index.html
{% extends "common/l_sidebar.html" %}
{% load static %}

{% block page_title %}レザーマチョナイズ{% endblock %}

{% block extra_head %}
<!-- slickのCSS -->
<link href="{% static 'common/css/slick/slick-theme.css' %}" rel="stylesheet">
<link href="{% static 'common/css/slick/slick.css' %}" rel="stylesheet">
<!-- slickのJS -->
<script src="{% static 'common/js/slick/slick.min.js' %}"></script>

<!--homeのCSSとJS-->
<script src="{% static 'home/js/script.js' %}"></script>
<link rel="stylesheet" href="{% static 'home/css/style.css' %}">
{% endblock %}



{% block main %}

<div class="slider">
    <div class="slider_content"><a href="{% url 'staff:index' %}"><img class="content_img" src="{% static 'home/img/slide/gym.jpg' %}" alt="背景画像"></a></div>
    <div class="slider_content"><a href="{% url 'movie:index' %}"><img class="content_img" src="{% static 'home/img/slide/home1.jpg' %}" alt="背景画像"></a></div>
    <div class="slider_content"><a href="{% url 'shop:index' %}"><img class="content_img" src="{% static 'home/img/slide/home2.jpg' %}" alt="背景画像"></a></div>
    <div class="slider_content"><a href=""><img class="content_img" src="{% static 'home/img/slide/home3.jpg' %}" alt="背景画像"></a></div>
</div>


<main>

    <div class="main_header" style="background-image: url({% static 'home/img/slide/home1.jpg' %});">
        <h2 class="sub_title">GYM</h2>
    </div>

    <div class="main_content">


        <p class="sentence">夏に映える筋肉美。筋肉の底から湧き出る爽やかさ。これだけでも理想のマッチョでしょう。だけどもうちょっとだけ筋肉にスパイスを加えて筋肉に花を咲かせよう。それがレザーマチョナイズ。「Business　Leather 灰汁取りー」とコラボして筋肉を最高に引き立てるレザーグッズを作り上げた。ジムで筋肉美を手に入れ、レザーを身に纏い、なんとも言えない絶妙な男らしさを醸し出しながら、マッスル人生を築き上げよう。</p>

    </div>

    <div class="main_header" style="background-image: url({% static 'home/img/slide/home1.jpg' %});">
        <h2>STAFF</h2>
    </div>

    <div class="main_content">

    </div>
</main>

{% endblock %}

templates/movie/content.html
{% extends "common/l_sidebar.html" %}
{% load static %}


{% block page_title %}動画ページ{% endblock %}


{% block extra_head %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
{% endblock %}



{% block main %}

    <main class="container">

    <!--DBから手に入れたデータをループ処理で描画していく。-->
    {% for content in data %}
    <div class="my-1 border">
        <!--models.pyで定義したフィールドの属性名を指定する(filenameは動画ファイル名、titleは動画タイトル)
            波括弧を使用して変数を表示、もしくは処理を実行させる。詳しくは教科書のP69を参照
        -->
        <h1>{{ content.title }}</h1>
        <video src="{% static 'movie/video/' %}{{ content.filename }}" controls></video>
    </div>
    {% endfor %}

    </main>

{% endblock %}

templates/movie/index.html
{% extends "common/l_sidebar.html" %}
{% load static %}


{% block page_title %}動画一覧{% endblock %}


{% block extra_head %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'movie/css/style.css' %}">
<link rel="stylesheet" href="{% static 'movie/css/new_style.css' %}">


<script src="{% static 'movie/js/jquery.inview.js' %}"></script>
<script src="{% static 'movie/js/animation.js' %}"></script>

{% endblock %}



{% block main %}

    <main id="mainarea" class="container">

        <section id="aboutme">
            
            <div class="section_header_area">
                <div class="section_header_shadow">動画サイト</div>
                <div class="section_header">動画サイト</div>
            </div>


            <!--    TIPS:スタッフの画像と紹介テキストを互い違いにすることで、見る側にマンネリ感を与えないようにすることができる。
                さらにアニメーションを使うことでユーザーのページ離脱を防ぐ
            -->
            {% for content in data %}
            <div class="row about_staff_row">
                <div class="col-sm-4 text-left" >
                    <video class="col-sm-12" src="{% static 'movie/video/' %}{{ content.filename }}" controls></video>
                </div>
                <div class="col-sm-8 align-self-center">
                    <div class="row my-2 text-left" style="font-size:0.9rem;">
                        <div class="col-3 my-1">動画タイトル</div><div class="col-9 my-1" >{{ content.title }}</div>
                        <div class="col-3 my-1">説明</div><div class="col-9 my-1" >{{ content.description }}</div>
                    </div>
                </div>
            </div>
            {% endfor %}


            <!--テンプレートの部品化はincludeでできる。テンプレート変数も読み込みできる。ただしload staticを忘れずに。-->
            <!--{% include "staff/include.html" %}  -->


            
        </section>

    </main>







{% endblock %}

templates/shop/index.html
{% extends "common/l_sidebar.html" %}
{% load static %}

<!--カンマ区切りで必要になる load humanize -->
{% load humanize %}




{% block page_title %}ショップ{% endblock %}


{% block extra_head %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'shop/css/style.css' %}">
<link rel="stylesheet" href="{% static 'shop/css/new_style.css' %}">


<script src="{% static 'shop/js/jquery.inview.js' %}"></script>
<script src="{% static 'shop/js/animation.js' %}"></script>

{% endblock %}



{% block main %}

    <main id="mainarea" class="container">

        <section id="aboutme">
            
            <div class="section_header_area">
                <div class="section_header_shadow">Shop</div>
                <div class="section_header">Shop</div>
            </div>


            <!--    TIPS:商品の画像と紹介テキストを互い違いにすることで、見る側にマンネリ感を与えないようにすることができる。
                さらにアニメーションを使うことでユーザーのページ離脱を防ぐ
            -->
            {% for content in data %}
            <div class="row about_staff_row">
                <div class="col-sm-4 text-left" >
                    <img class="col-sm-12" src="{% static 'shop/img/' %}{{ content.filename }}" alt="No images" >
                </div>
                <div class="col-sm-8 align-self-center">
                    <div class="row my-2 text-left" style="font-size:0.9rem;">
                        <div class="col-3 my-1">商品名</div><div class="col-9 my-1" >{{ content.goodsname }}</div>
                        <!--intcommaでカンマ区切りに-->
                        <div class="col-3 my-1">金額</div><div class="col-9 my-1" >￥{{ content.price|intcomma }}</div>
                        <div class="col-3 my-1">商品説明</div><div class="col-9 my-1" >{{ content.comment }}</div>
                    </div>
                </div>
            </div>
            {% endfor %}


            <!--テンプレートの部品化はincludeでできる。テンプレート変数も読み込みできる。ただしload staticを忘れずに。-->
            {# {% include "staff/include.html" %}  #}


            
        </section>

    </main>







{% endblock %}

templates/staff/include.html
{% load static %}

{% for content in data %}
<div class="row about_staff_row">
    <div class="col-sm-4 text-left" >
        <img class="col-sm-12" src="{% static 'staff/img/staffpic_edited/' %}{{ content.filename }}" alt="Adam Smith" >
    </div>
    <div class="col-sm-8 align-self-center">
        <div class="row my-2 text-left" style="font-size:0.9rem;">
            <div class="col-3 my-1">氏名</div><div class="col-9 my-1" >{{ content.staffname }}</div>
            <div class="col-3 my-1">チャームポイント</div><div class="col-9 my-1" >{{ content.bestmuscle }}</div>
            <div class="col-3 my-1">トレーニング歴</div><div class="col-9 my-1" >{{ content.workouthistory }}</div>
            <div class="col-3 my-1">一言</div><div class="col-9 my-1" >{{ content.comment }}</div>
        </div>
    </div>
</div>
{% endfor %}

templates/staff/index.html
{% extends "common/l_sidebar.html" %}
{% load static %}


{% block page_title %}スタッフ一覧{% endblock %}


{% block extra_head %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'staff/css/style.css' %}">
<link rel="stylesheet" href="{% static 'staff/css/new_style.css' %}">


<script src="{% static 'staff/js/jquery.inview.js' %}"></script>
<script src="{% static 'staff/js/animation.js' %}"></script>

{% endblock %}



{% block main %}

    <main id="mainarea" class="container">

        <section id="aboutme">
            
            <div class="section_header_area">
                <div class="section_header_shadow">About_staff</div>
                <div class="section_header">About_staff</div>
            </div>


            <!--    TIPS:スタッフの画像と紹介テキストを互い違いにすることで、見る側にマンネリ感を与えないようにすることができる。
                さらにアニメーションを使うことでユーザーのページ離脱を防ぐ
            -->
            {% for content in data %}
            <div class="row about_staff_row">
                <div class="col-sm-4 text-left" >
                    <img class="col-sm-12" src="{% static 'staff/img/staffpic_edited/' %}{{ content.filename }}" alt="Adam Smith" >
                </div>
                <div class="col-sm-8 align-self-center">
                    <div class="row my-2 text-left" style="font-size:0.9rem;">
                        <div class="col-3 my-1">氏名</div><div class="col-9 my-1" >{{ content.staffname }}</div>
                        <div class="col-3 my-1">チャームポイント</div><div class="col-9 my-1" >{{ content.bestmuscle }}</div>
                        <div class="col-3 my-1">トレーニング歴</div><div class="col-9 my-1" >{{ content.workouthistory }}</div>
                        <div class="col-3 my-1">一言</div><div class="col-9 my-1" >{{ content.comment }}</div>
                    </div>
                </div>
            </div>
            {% endfor %}


            <!--テンプレートの部品化はincludeでできる。テンプレート変数も読み込みできる。ただしload staticを忘れずに。-->
            <!--{% include "staff/include.html" %}  -->


            
        </section>

    </main>







{% endblock %}